name: Rust Formatting & Linting check

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint:
    name: Check Formatting & Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check Formatting
        run: cargo fmt --check

      - name: Run Clippy Linter
        run: cargo clippy -- -D warnings